source "https://rubygems.org"

gem "rails", "~> 7.2.2", ">= 7.2.2.1"
gem "sqlite3", ">= 1.4"
gem "pg", "~> 1.5"
gem "puma", ">= 5.0"
gem "rack-cors"
gem "omniauth"
gem "omniauth-google-oauth2"
gem "pdf-reader"
gem "roo"

gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

group :development, :test do
  gem "dotenv-rails"
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "rspec-rails"
  gem "rswag-api"
  gem "rswag-specs"
  gem "webmock"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end
